config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'products#index'
  resources :pens, controller: 'products', type: 'Pen'
	resources :notebooks, controller: 'products', type: 'Notebook' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notebook.rb
class Notebook < Product
end	 

app/models/pen.rb
class Pen < Product
	validates :color, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, numericality: true
  validates :inward_date, inclusion: { in: proc { 1.month.ago..Date.today } }  
  self.inheritance_column = :type  
  TYPES = ["Notebook", "Pen"]

  def self.price_sum(product_type)
    where(type: product_type).sum(:price)
  end    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_type, only: [:new]

  def index
    @products = Product.all.decorate
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @type = product_params[:type] if product_params[:type].present?
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private

  def set_type 
    @type = type 
  end

  def type 
    Product::TYPES.include?(params[:type]) ? params[:type] : "Product"
  end

  def type_class 
    type.constantize 
  end

  def set_product
    @product = type_class.find(params[:id])
  end

  def product_params
    params.require(type.underscore.to_sym).permit(:name, :price, :inward_date, :type, :color) 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title>ProductCatalog</title>
	  <%= csrf_meta_tags %>
	  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	  <%= javascript_include_tag "bootstrap-datepicker"%>
	  <%= stylesheet_link_tag "datepicker" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<script>
 $(document).ready(function(){
  $('.datepicker').datepicker( {
    format: 'dd-mm-yyyy',
      startDate: '-1m',
      endDate: '0d'
    });
});
</script>

<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :inward_date %>
    <%= form.text_field :inward_date, :class => "datepicker"%>
  </div>
  <%= form.hidden_field :type, :value => @type %>

  <% if @type == 'Pen' %>
    <div class="field">
      <%= form.label :color %>
      <%= form.text_field :color, id: :product_color %>
    </div>
  <% end %>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/index.html.erb
<div class="container">
<br/>
  <div class="row">
    <div class="dropdown">
      <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Add Product
      <span class="caret"></span></button>
      <ul class="dropdown-menu">
        <% Product::TYPES.each do |product_type| %>
          <li><a href="<%= new_product_path(type: product_type)%>"><%= product_type%></a></li>
        <% end %>  
      </ul>
    </div>
  </div>
<br/> 
<p id="notice"><%= notice %></p>
<br/>

<h1>Products</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Inward date</th>
      <th>Type</th>
      <th>Color</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.formatted_inward_date %></td>
        <td><%= product.type %></td>
        <td><%= product.color %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/products/new.html.erb
<div class="container">
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>
</div>